// @vitest-environment node
import { describe, it, expect } from 'vitest';
import {
  deepMerge,
  fullCompanyConfig,
  rewriteAssetRefs,
  stratosYaml,
  basename,
  ASSET_URL_BASE,
} from '@/emit/stratos-target';

describe('deepMerge', () => {
  it('merges nested objects rather than replacing them', () => {
    const base = { logos: { main: 'a.png', navigation: 'b.png' } };
    expect(deepMerge(base, { logos: { main: 'new.png' } })).toEqual({
      logos: { main: 'new.png', navigation: 'b.png' },
    });
  });

  it('replaces arrays wholesale', () => {
    expect(deepMerge({ a: [1, 2, 3] }, { a: [9] })).toEqual({ a: [9] });
  });

  it('ignores undefined values in the patch', () => {
    expect(deepMerge({ a: 'keep' }, { a: undefined })).toEqual({ a: 'keep' });
  });

  it('does not mutate its inputs', () => {
    const base = { logos: { main: 'a.png' } };
    const patch = { logos: { main: 'b.png' } };
    deepMerge(base, patch);
    expect(base.logos.main).toBe('a.png');
    expect(patch.logos.main).toBe('b.png');
  });
});

describe('fullCompanyConfig', () => {
  // The sparse patch is what blanks sibling keys in the consumer; emitting a
  // complete document is the emit-side half of that fix.
  const shipped = {
    company: { name: 'Stratos', website: 'https://stratos.app' },
    logos: { main: '/core/assets/logo.png', navigation: '/core/assets/logo.png', favicon: '/favicon.ico' },
    theme: { primary: '#3b82f6', danger: '#ef4444' },
  };

  it('keeps sibling keys the patch does not mention', () => {
    const out = fullCompanyConfig(shipped, { logos: { main: 'logo.svg' } }) as typeof shipped;
    expect(out.logos.main).toBe('logo.svg');
    expect(out.logos.navigation).toBe('/core/assets/logo.png');
    expect(out.logos.favicon).toBe('/favicon.ico');
  });

  it('keeps whole top-level sections the patch omits', () => {
    const out = fullCompanyConfig(shipped, { theme: { primary: '#0f74c5' } }) as typeof shipped;
    expect(out.company.name).toBe('Stratos');
    expect(out.theme.danger).toBe('#ef4444');
    expect(out.theme.primary).toBe('#0f74c5');
  });
});

describe('rewriteAssetRefs', () => {
  it('rewrites bare filenames that name an emitted asset', () => {
    const config = { logos: { main: 'logo.svg' } };
    expect(rewriteAssetRefs(config, ['assets/logo.svg'])).toEqual({
      logos: { main: `${ASSET_URL_BASE}/logo.svg` },
    });
  });

  it('leaves strings that name no emitted asset alone', () => {
    const config = { logos: { main: '/core/assets/logo.png' }, company: { name: 'Stratos' } };
    expect(rewriteAssetRefs(config, ['assets/logo.svg'])).toEqual(config);
  });

  it('rewrites through nested objects and arrays', () => {
    const config = { a: { b: ['logo.svg', 'keep'] } };
    expect(rewriteAssetRefs(config, ['logo.svg'])).toEqual({
      a: { b: [`${ASSET_URL_BASE}/logo.svg`, 'keep'] },
    });
  });

  it('leaves non-string values untouched', () => {
    const config = { showLogo: true, pageSize: 9, nothing: null };
    expect(rewriteAssetRefs(config, ['logo.svg'])).toEqual(config);
  });

  it('is idempotent — a rewritten ref is no longer a bare filename', () => {
    const once = rewriteAssetRefs({ logo: 'logo.svg' }, ['logo.svg']);
    expect(rewriteAssetRefs(once, ['logo.svg'])).toEqual(once);
  });
});

describe('basename', () => {
  it('strips the assets/ prefix stb stores refs with', () => {
    expect(basename('assets/logo.svg')).toBe('logo.svg');
  });

  it('passes a bare filename through', () => {
    expect(basename('logo.svg')).toBe('logo.svg');
  });
});

describe('stratosYaml', () => {
  it('emits a title', () => {
    expect(stratosYaml({ title: 'Acme Console' })).toContain('title: "Acme Console"');
  });

  it('quotes a title containing YAML-significant characters', () => {
    expect(stratosYaml({ title: 'Acme: the console' })).toContain('title: "Acme: the console"');
  });

  it('emits an exclude list', () => {
    const out = stratosYaml({ exclude: ['@stratosui/kubernetes'] });
    expect(out).toContain('packages:');
    expect(out).toContain('    - "@stratosui/kubernetes"');
  });

  it('emits include, exclude and desktop together', () => {
    const out = stratosYaml({ include: ['@example/theme'], exclude: ['@stratosui/git'], desktop: true });
    expect(out).toContain('  desktop: true');
    expect(out).toContain('  include:');
    expect(out).toContain('  exclude:');
  });

  it('omits the packages block entirely when nothing is configured', () => {
    expect(stratosYaml({ title: 'Acme' })).not.toContain('packages:');
  });

  it('always carries the generated-file warning and a trailing newline', () => {
    const out = stratosYaml({ title: 'Acme' });
    expect(out.startsWith('# Generated by stb')).toBe(true);
    expect(out.endsWith('\n')).toBe(true);
  });
});
