/**
 * Emitters for the Stratos build inputs that are fully specified today:
 * the company config, brand assets, and `stratos.yaml`.
 *
 * Every path below was read off `angular.json` / `build/*` rather than assumed —
 * each artefact is consumed inside a single `make build` run, so writing them is
 * a pre-build step needing no build changes.
 *
 * Pure object/string work. The filesystem lives in scripts/emit-to-stratos.ts.
 */

/** Where each artefact must land for the build to pick it up. */
export const TARGETS = {
  /** angular.json assets[] → served at /assets/company-config.json */
  companyConfig: 'src/frontend/packages/theme/company-config.json',
  /** angular.json assets[] → served at /core/assets/custom */
  assetDir: 'custom-src/frontend/assets/custom',
  /** read by build/extension-generator.mjs and build/index-transformer.js */
  stratosYaml: 'stratos.yaml',
} as const;

/** Public URL base for files written into TARGETS.assetDir. */
export const ASSET_URL_BASE = '/core/assets/custom';

type JsonObject = { [key: string]: unknown };

function isPlainObject(v: unknown): v is JsonObject {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/** Recursive merge. Objects merge; arrays and scalars replace wholesale. */
export function deepMerge<T extends JsonObject>(base: T, patch: JsonObject): T {
  const out: JsonObject = { ...base };
  for (const [key, value] of Object.entries(patch)) {
    if (value === undefined) continue;
    const existing = out[key];
    out[key] = isPlainObject(existing) && isPlainObject(value) ? deepMerge(existing, value) : value;
  }
  return out as T;
}

/**
 * Produce a COMPLETE company config from stb's sparse patch.
 *
 * The consumer merges one level deep, so a sparse config blanks sibling keys —
 * emitting a complete document sidesteps that entirely and needs no consumer
 * change. Sparse output is what makes `logos.navigation` and friends go
 * undefined; this is the emit-side half of that fix.
 */
export function fullCompanyConfig(shipped: JsonObject, patch: JsonObject): JsonObject {
  return deepMerge(shipped, patch);
}

/**
 * Rewrite bare asset filenames to URLs the running console can actually fetch.
 *
 * stb records refs as bare filenames (`logo.svg`), which resolve against
 * whatever route the browser is on. Only strings that name a file we are
 * actually writing get rewritten, so unrelated config strings are untouched.
 */
export function rewriteAssetRefs<T>(config: T, assetFilenames: Iterable<string>): T {
  const known = new Set<string>();
  for (const f of assetFilenames) known.add(basename(f));

  const walk = (node: unknown): unknown => {
    if (typeof node === 'string') {
      return known.has(node) ? `${ASSET_URL_BASE}/${node}` : node;
    }
    if (Array.isArray(node)) return node.map(walk);
    if (isPlainObject(node)) {
      const out: JsonObject = {};
      for (const [k, v] of Object.entries(node)) out[k] = walk(v);
      return out;
    }
    return node;
  };

  return walk(config) as T;
}

/** Last path segment, for refs stored as `assets/<filename>`. */
export function basename(ref: string): string {
  const i = ref.lastIndexOf('/');
  return i === -1 ? ref : ref.slice(i + 1);
}

export interface StratosYamlInput {
  /** Browser/document title. Falls back to "Stratos" in the transformer. */
  title?: string;
  /** Angular packages to leave out of the build. */
  exclude?: string[];
  /** Packages to force in, overriding the generator's default excludes. */
  include?: string[];
  /** Build the desktop extensions package. */
  desktop?: boolean;
}

/**
 * Emit `stratos.yaml`. Hand-written rather than pulled through a YAML library —
 * the document is a title and two string lists, and JSON scalars are valid
 * YAML double-quoted scalars, so quoting is already handled correctly.
 */
export function stratosYaml(input: StratosYamlInput): string {
  const lines: string[] = ['# Generated by stb. Edits here are overwritten on the next emit.'];

  if (input.title) lines.push(`title: ${JSON.stringify(input.title)}`);

  const { include = [], exclude = [], desktop } = input;
  if (include.length || exclude.length || desktop !== undefined) {
    lines.push('packages:');
    if (desktop !== undefined) lines.push(`  desktop: ${desktop}`);
    for (const [key, list] of [
      ['include', include],
      ['exclude', exclude],
    ] as const) {
      if (!list.length) continue;
      lines.push(`  ${key}:`);
      for (const pkg of list) lines.push(`    - ${JSON.stringify(pkg)}`);
    }
  }

  return lines.join('\n') + '\n';
}
